### ISSUE TITLE
Release latest GitHub source code on PyPi

### ISSUE THREAD

**Issue by codrin-lanterne** [lyang/pynamodb-encoder#123]
Hi, thank you for putting this library together, it's extremly useful!

I noticed the latest PyPi released version doesn't contain [this change](https://github.com/lyang/pynamodb-encoder/commit/85d739ab23192e687bf322097cdeb5c46b148448). Do you think it would be possible to release the latest GitHub source code on PyPi?

Cheers

**Comment by lyang** [comment]
Hi @codrin-lanterne,
Glad you find it useful 😊
I'm currently away from my dev environment. I can definitely do the release shortly after the Chinese New Year.
Thanks!

**Comment by codrin-lanterne** [comment]
Awesome, thank you! Hope you have a great new year 🎉

**Comment by houbie** [comment]
Any news on this?

**Comment by codrin-lanterne** [comment]
+1 to this just because I encountered today another issue this could fix, thanks a lot and sorry for the spam, maybe you have other priorities so no worries just in case this slipped through

**Comment by lyang** [comment]
Hi All,
Really sorry for the late response. I just relocated entire family across continents, a bit swamped right now.
Hopefully I will be able to squeeze out some time next week for the push.

Thanks!

**Comment by lyang** [comment]
So sorry for the long delay, v0.1.2 was just published 🥳
